name: DCE Terraform Deploy
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TEAM: of
      ENVIRONEMT: production
      LOCATION: eastus
      ARM_CLIENT_ID: 7c8e6ffe-4a06-41bd-ac7e-4a7dd5b7d067
      ARM_CLIENT_SECRET: _5F8Q~qcyqlFVJAO0J8wkNWer4g94NRiptubfdBr
      ARM_SUBSCRIPTION_ID: 14794eab-e638-4c6e-9e78-33c378312767
      ARM_TENANT_ID: fac4f30d-a2ea-4dda-9871-1dc986c702bd
    name: "Terraform Deploy"
    steps:
      - uses: actions/checkout@v3
      - name: Install Azure CLI
        run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      - name: Install Terraform
        run: |
          sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
          wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt-get install terraform
      - name: Az Login
        run: az login --service-principal -u "9bba227c-06dd-4b89-8635-301eb06d742b" -p "_5F8Q~qcyqlFVJAO0J8wkNWer4g94NRiptubfdBr" --tenant "fac4f30d-a2ea-4dda-9871-1dc986c702bd"
        timeout-minutes: 1
      - name: Bootstrap
        run: ./prerequisite_resources.sh $TEAM $ENVIRONEMT $LOCATION
        working-directory: bootstrap
      - name: Set TF State Access
        run: |
          ARM_ACCESS_KEY=$(az storage account keys list --account-name "st${TEAM}${ENVIRONEMT}tfstate" --query "[0].value" | tr -d '"')
          echo "ARM_ACCESS_KEY=${ARM_ACCESS_KEY}" >> $GITHUB_ENV
      - name: "Terraform Init Azure Cloud"
        run: terraform init -backend-config dce/backend.tf
        working-directory: terraform/azure-cloud
      - name: "Terraform Plan Azure Cloud"
        run: terraform plan --var-file dce/variables.tfvars -out tfplan
        working-directory: terraform/azure-cloud
      - name: 'Terraform Apply Azure Cloud'
        run: terraform apply tfplan
        working-directory: terraform/azure-cloud
      # - name: "Terraform Init On-Premise"
      #   run: terraform init -backend-config dce/backend.tf
      #   working-directory: terraform/on-premise
      # - name: "Terraform Plan On-Premise"
      #   run: terraform plan -var 'PriMsId=jgrif106' -var 'PriMsIdPwd=${{ secrets.PRI_MS_ID_PWD }}' -out tfplan
      #   working-directory: terraform/on-premise
      # - name: 'Terraform Apply On-Premise'
      #   run: terraform apply tfplan
      #   working-directory: terraform/on-premise
