name: Prod Terraform Deploy
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: uhg-runner
    env:
      TEAM: of
      ENVIRONEMT: prod
      LOCATION: centralus
      ARM_CLIENT_ID: 23125f23-1504-4bc7-91fa-1a7fa4adc7b5
      ARM_CLIENT_SECRET: ${{ secrets.PROD_ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: 709dbaf7-b13c-4ac3-b4a8-de593db254f3
      ARM_TENANT_ID: db05faca-c82a-4b9d-b9c5-0f64b6755421
    name: "Terraform Deploy"
    steps:
      - uses: actions/checkout@v3
      - name: Install Azure CLI
        run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      - name: Install Terraform
        run: |
          sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
          wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt-get install terraform
      - name: Az Login
        run: az login --service-principal -u $ARM_CLIENT_ID -p=$ARM_CLIENT_SECRET  --tenant $ARM_TENANT_ID
        timeout-minutes: 1
      - name: Bootstrap
        run: ./prerequisite_resources.sh $TEAM $ENVIRONEMT $LOCATION
        working-directory: bootstrap
      - name: Set TF State Access
        run: |
          ARM_ACCESS_KEY=$(az storage account keys list --account-name "st${TEAM}${ENVIRONEMT}tfstate" --query "[0].value" | tr -d '"')
          echo "ARM_ACCESS_KEY=${ARM_ACCESS_KEY}" >> $GITHUB_ENV
      - name: "Git Config URL"
        run: git config --global url."https://jgrif106:${{ secrets.GH_PAT }}@github.com".insteadOf "https://github.com"
      - name: "Terraform Init Azure Cloud"
        run: terraform init -backend-config prod/backend.tf
        working-directory: terraform/azure-cloud
      - name: "Terraform Plan Azure Cloud"
        run: terraform plan --var-file prod/variables.tfvars -out tfplan
        working-directory: terraform/azure-cloud
      - name: 'Terraform Apply Azure Cloud'
        run: terraform apply tfplan
        working-directory: terraform/azure-cloud

